@extends('page-layout.master')
@section('section')
    @if(app()->getLocale() === 'vi')
        @include('pages.home-page.section-1')
    @elseif(app()->getLocale() === 'en')
        @include('pages.home-page.section-1-eng')
    @elseif(app()->getLocale() === 'ja')
        @include('pages.home-page.section-1-ja')
    @endif
    @if(app()->getLocale() === 'vi')
        @include('pages.home-page.sec2')
    @elseif(app()->getLocale() === 'en')
        @include('pages.home-page.sec2')
    @elseif(app()->getLocale() === 'ja')
        @include('pages.home-page.sec2-jp')
    @endif
    @if(app()->getLocale() === 'vi')
        @include('pages.home-page.sec3')
    @elseif(app()->getLocale() === 'en')
        @include('pages.home-page.sec3-eng')
    @elseif(app()->getLocale() === 'ja')
        @include('pages.home-page.sec3-ja')
    @endif
    @include('pages.home-page.section-5')
    @include('pages.home-page.section-6')
    @include('pages.home-page.section-7')
    @if(app()->getLocale() === 'vi')
        @include('pages.home-page.sec7-v')
    @elseif(app()->getLocale() === 'en')
        @include('pages.home-page.sec7-v')
    @elseif(app()->getLocale() === 'ja')
        @include('pages.home-page.sec7-v-jp')
    @endif
@stop
